from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from assistant.contracts import AssistantState
from assistant.router import AssistantRouter
from assistant.state import load_state, save_state


class AssistantRouterHeuristicTest(unittest.TestCase):
    def setUp(self) -> None:
        self.router = AssistantRouter()

    def test_routes_time_source_and_general_concept_requests(self) -> None:
        state = AssistantState(session_id="test")

        time_route = self.router.route("qué día es hoy?", state)
        date_route = self.router.route("what date is it?", state)
        source_route = self.router.route("de dónde proviene tu información?", state)
        search_scope_route = self.router.route("qué puedes buscar?", state)
        agent_scope_route = self.router.route("qué puede hacer cada uno?", state)
        column_route = self.router.route("what is a column?", state)
        variable_route = self.router.route("what is a variable?", state)
        comparison_route = self.router.route("qué diferencia hay entre variables y columnas?", state)
        row_route = self.router.route("what is a row?", state)
        schema_route = self.router.route("what is a schema?", state)
        data_help_route = self.router.route("what can I do with the data?", state)
        dataset_route = self.router.route("what is a dataset?", state)
        artifact_route = self.router.route("what is an artifact?", state)
        manifest_route = self.router.route("what is a manifest?", state)
        target_route = self.router.route("what is a target?", state)
        feature_engineering_route = self.router.route("what is feature engineering?", state)
        grounding_route = self.router.route("what is grounding?", state)
        memory_route = self.router.route("what is memory?", state)
        artifact_store_route = self.router.route("what is an artifact store?", state)
        evidence_ledger_route = self.router.route("what is an evidence ledger?", state)
        drift_route = self.router.route("what is drift?", state)
        conversational_layer_route = self.router.route("what is a conversational layer?", state)
        validator_route = self.router.route("what is a validator?", state)
        shadow_run_route = self.router.route("what is a shadow run?", state)
        promotion_gate_route = self.router.route("what is a promotion gate?", state)
        challenger_comparison_route = self.router.route("what is the difference between challenger and champion?", state)
        policy_engine_route = self.router.route("what is a policy engine?", state)
        retraining_scheduler_route = self.router.route("what is a retraining scheduler?", state)
        feature_registry_route = self.router.route("what is a feature registry?", state)
        adaptive_selector_route = self.router.route("what is an adaptive selector?", state)
        shadow_runner_route = self.router.route("what is a shadow runner?", state)
        promotion_policy_route = self.router.route("what is a promotion policy?", state)
        do_with_that_route = self.router.route("what do I do with that?", state)
        next_step_route = self.router.route("what should I do next?", state)
        next_step_es_route = self.router.route("qué hago ahora?", state)

        self.assertEqual(time_route.intent, "show_time_status")
        self.assertEqual(date_route.intent, "show_time_status")
        self.assertEqual(source_route.intent, "show_source_scope")
        self.assertEqual(search_scope_route.intent, "show_source_scope")
        self.assertEqual(agent_scope_route.intent, "show_agent_guide")
        self.assertEqual(column_route.intent, "show_semantic_lookup")
        self.assertEqual(variable_route.intent, "show_semantic_lookup")
        self.assertEqual(comparison_route.intent, "show_semantic_lookup")
        self.assertEqual(row_route.intent, "show_semantic_lookup")
        self.assertEqual(schema_route.intent, "show_semantic_lookup")
        self.assertEqual(data_help_route.intent, "help")
        self.assertEqual(dataset_route.intent, "show_semantic_lookup")
        self.assertEqual(artifact_route.intent, "show_semantic_lookup")
        self.assertEqual(manifest_route.intent, "show_semantic_lookup")
        self.assertEqual(target_route.intent, "show_semantic_lookup")
        self.assertEqual(feature_engineering_route.intent, "show_semantic_lookup")
        self.assertEqual(grounding_route.intent, "show_semantic_lookup")
        self.assertEqual(memory_route.intent, "show_semantic_lookup")
        self.assertEqual(artifact_store_route.intent, "show_semantic_lookup")
        self.assertEqual(evidence_ledger_route.intent, "show_semantic_lookup")
        self.assertEqual(drift_route.intent, "show_semantic_lookup")
        self.assertEqual(conversational_layer_route.intent, "show_semantic_lookup")
        self.assertEqual(validator_route.intent, "show_semantic_lookup")
        self.assertEqual(shadow_run_route.intent, "show_semantic_lookup")
        self.assertEqual(promotion_gate_route.intent, "show_semantic_lookup")
        self.assertEqual(challenger_comparison_route.intent, "show_semantic_lookup")
        self.assertEqual(policy_engine_route.intent, "show_semantic_lookup")
        self.assertEqual(retraining_scheduler_route.intent, "show_semantic_lookup")
        self.assertEqual(feature_registry_route.intent, "show_semantic_lookup")
        self.assertEqual(adaptive_selector_route.intent, "show_semantic_lookup")
        self.assertEqual(shadow_runner_route.intent, "show_semantic_lookup")
        self.assertEqual(promotion_policy_route.intent, "show_semantic_lookup")
        self.assertEqual(do_with_that_route.intent, "help")
        self.assertEqual(next_step_route.intent, "help")
        self.assertEqual(next_step_es_route.intent, "help")

    def test_routes_semantic_lookup_questions_without_breaking_metrics(self) -> None:
        state = AssistantState(session_id="test")

        semantic_en_route = self.router.route("what does forex mean?", state)
        semantic_es_route = self.router.route("qué es forex?", state)
        yfinance_route = self.router.route("what is yfinance?", state)
        bare_yfinance_route = self.router.route("yfinance", state)
        metrics_route = self.router.route("what is the volume of NVDA?", state)

        self.assertEqual(semantic_en_route.intent, "show_semantic_lookup")
        self.assertEqual(semantic_es_route.intent, "show_semantic_lookup")
        self.assertEqual(yfinance_route.intent, "show_semantic_lookup")
        self.assertEqual(bare_yfinance_route.intent, "show_semantic_lookup")
        self.assertEqual(metrics_route.intent, "show_market_metrics")

    def test_routes_pure_greeting_and_greeting_plus_intent(self) -> None:
        state = AssistantState(session_id="test")

        greeting_route = self.router.route("hola", state)
        greeting_semantic_route = self.router.route("hola, qué es forex?", state)

        self.assertEqual(greeting_route.intent, "greet")
        self.assertEqual(greeting_route.stage, "greeting")
        self.assertEqual(greeting_semantic_route.intent, "show_semantic_lookup")

    def test_routes_run_request_with_ticker_and_dates(self) -> None:
        state = AssistantState(session_id="test")
        route = self.router.route("run BTC-USD from Jan to Mar", state)

        self.assertEqual(route.intent, "run_pipeline")
        self.assertIn("BTC-USD", route.tickers)
        self.assertEqual(route.interval, "1d")
        self.assertIsNotNone(route.start)
        self.assertIsNotNone(route.end)

    def test_routes_test_and_forex_prompts_with_defaults(self) -> None:
        state = AssistantState(session_id="test")

        default_route = self.router.route("select it you, make a test", state)
        forex_route = self.router.route("i want the price of an forex active", state)
        forex_extract_route = self.router.route("extract info about a forex action from yfinance", state)

        self.assertEqual(default_route.intent, "run_pipeline")
        self.assertEqual(default_route.tickers, ["AAPL"])
        self.assertIsNotNone(default_route.start)
        self.assertIsNotNone(default_route.end)

        self.assertEqual(forex_route.intent, "run_pipeline")
        self.assertEqual(forex_route.tickers, ["EURUSD=X"])
        self.assertIsNotNone(forex_route.start)
        self.assertIsNotNone(forex_route.end)

        self.assertEqual(forex_extract_route.intent, "run_pipeline")
        self.assertEqual(forex_extract_route.tickers, ["EURUSD=X"])

    def test_routes_summary_and_legacy_requests(self) -> None:
        state = AssistantState(session_id="test")

        summary_route = self.router.route("summarize the latest run", state)
        legacy_route = self.router.route("what is the legacy status?", state)
        help_route = self.router.route("what u can do ?", state)
        ask_route = self.router.route("how i can ask u ?", state)
        help_me_route = self.router.route("how can you help me?", state)
        switch_es_route = self.router.route("switch to Spanish", state)
        switch_en_route = self.router.route("switch to English", state)
        spanish_route = self.router.route("answer in Spanish what did the model predict?", state)
        sticky_spanish_state = AssistantState(session_id="test", preferred_language="es")
        sticky_spanish_route = self.router.route("what symbol was used?", sticky_spanish_state)
        extract_help_route = self.router.route("how can you help me to extract info from yfinance?", state)
        search_route = self.router.route("can u search info from yfinance on internet ?", state)
        symbols_route = self.router.route("what symbols can I use?", state)
        spanish_symbols_route = self.router.route("que simbolos puedo usar?", state)
        asset_used_route = self.router.route("what symbol was used?", state)
        asset_used_es_route = self.router.route("qué símbolo se usó?", state)
        clean_data_route = self.router.route("show the clean market data open high", state)
        clean_data_hub_route = self.router.route("clean data", state)
        clean_data_hub_es_route = self.router.route("datos limpios", state)
        clean_symbols_route = self.router.route("what symbols are in the cleaned data?", state)
        clean_metrics_route = self.router.route("what metrics are in the cleaned data?", state)
        clean_metrics_es_route = self.router.route("qué métricas hay en los datos limpios?", state)
        clean_schema_route = self.router.route("what is the clean data schema?", state)
        clean_row_bare_route = self.router.route("fila", state)
        clean_row_row_route = self.router.route("row", state)
        clean_row_natural_route = self.router.route("qué dice esta fila limpia?", state)
        clean_row_analysis_keyword_route = self.router.route("análisis de fila", state)
        clean_row_route = self.router.route("show the clean row for MSFT on 2026-03-21 open high", state)
        clean_row_analysis_route = self.router.route("analyze the clean row for MSFT on 2026-03-21", state)
        clean_row_analysis_es_route = self.router.route("analiza la fila limpia de MSFT el 2026-03-21", state)
        extraction_report_route = self.router.route("qué columnas se extrajeron?", state)
        extraction_report_en_route = self.router.route("what columns were extracted?", state)
        market_metrics_route = self.router.route("what is the volume of NVDA?", state)
        market_metrics_es_route = self.router.route("qué es la volatilidad de AAPL?", state)
        market_metrics_fx_route = self.router.route("cuál es el volumen de EURUSD?", state)
        market_metrics_ambiguous_route = self.router.route("cuál es el volumen de X?", state)
        forex_extract_route = self.router.route("extract info about a forex action from yfinance", state)
        decision_route = self.router.route("how does clean data affect hold long short?", state)
        decision_route_es = self.router.route("cómo afecta la limpieza a long short hold?", state)
        last_run_route = self.router.route("show the last run", state)
        motor_route = self.router.route("what motor was used?", state)
        groq_status_route = self.router.route("what groq url is used?", state)
        session_status_route = self.router.route("status", state)
        session_status_full_route = self.router.route("status full", state)
        session_status_full_es_route = self.router.route("estado completo", state)
        mode_status_route = self.router.route("what mode am I in?", state)
        brain_status_route = self.router.route("am I in Groq brain?", state)
        mode_guide_route = self.router.route("local_only", state)
        groq_brain_mode_route = self.router.route("--groq-brain", state)
        mode_help_route = self.router.route("what modes can I use?", state)
        bare_mode_help_route = self.router.route("modos", state)
        agents_route = self.router.route("agents", state)
        bare_agents_route = self.router.route("agentes", state)
        shortcut_agents_route = self.router.route("1", state)
        shortcut_extraction_route = self.router.route("2", state)
        shortcut_cleaning_route = self.router.route("3", state)
        shortcut_modeling_route = self.router.route("4", state)
        shortcut_orchestrator_route = self.router.route("5", state)
        shortcut_status_route = self.router.route("6", state)
        shortcut_full_status_route = self.router.route("7", state)
        shortcut_clean_data_route = self.router.route("8", state)
        shortcut_modes_route = self.router.route("9", state)
        shortcut_help_route = self.router.route("H", state)
        shortcut_spanish_route = self.router.route("B", state)
        shortcut_english_route = self.router.route("N", AssistantState(session_id="test", preferred_language="es"))
        bare_extraction_route = self.router.route("Extracción", state)
        bare_cleaning_route = self.router.route("Limpieza", state)
        bare_modeling_route = self.router.route("Modelado", state)
        bare_orchestrator_route = self.router.route("Orquestador", state)
        bare_symbol_guide_route = self.router.route("símbolos", state)
        bare_mode_label_route = self.router.route("compare-binance", state)
        bare_ticker_route = self.router.route("AAPL", state)
        run_lookup_route = self.router.route("run_0007 what symbol was used?", state)
        bare_run_lookup_route = self.router.route("run_0007", state)
        run_cleaning_route = self.router.route("run_0007 limpieza", state)
        run_cleaning_question_route = self.router.route("run_0007 qué pasó en la limpieza?", state)
        run_modeling_route = self.router.route("run_0007 modelado", state)
        run_model_variables_route = self.router.route("run_0007 qué variables usó el modelo?", state)
        run_model_variables_mid_sentence_route = self.router.route("explica las variables usadas en run_0007", state)
        natural_model_variables_route = self.router.route("modelado que transformacion y variables explicativas utilizaste?", state)
        ask_extraction_card_route = self.router.route("ask extraction", state)
        ask_cleaning_card_route = self.router.route("ask cleaning", state)
        ask_modeling_card_route = self.router.route("ask modeling", state)
        groq_brain_route = self.router.route("run AAPL with groq brain", state)
        groq_extract_route = self.router.route("what did Groq say in extraction?", state)
        use_extraction_route = self.router.route("use extraction", state)
        groq_clean_route = self.router.route("what did Groq say in cleaning?", state)
        groq_model_route = self.router.route("what did Groq say in modeling?", state)
        groq_orch_route = self.router.route("what did Groq say in the orchestrator?", state)
        orchestrator_route = self.router.route("orquestador", state)
        ask_extraction_route = self.router.route("ask extraction what happened in the last run?", state)
        ask_cleaning_route = self.router.route("ask cleaning what columns were written?", state)
        ask_modeling_route = self.router.route("ask modeling why did it choose long?", state)
        ask_orchestrator_route = self.router.route("ask orchestrator why was the final decision chosen?", state)
        groq_here_route = self.router.route("what say groq here?", state)
        what_happened_route = self.router.route("what happened?", state)
        why_hold_route = self.router.route("why did it hold?", state)
        last_clean_route = self.router.route("clean the last extraction", state)
        last_extraction_route = self.router.route("tell me about the last extraction", state)
        last_model_route = self.router.route("tell me about the last model", state)
        share_extraction_route = self.router.route("share me about the last extraction in your words", state)
        share_combined_route = self.router.route("share me the last extraction and clean process in your words", state)
        extraction_clean_route = self.router.route("what u can toll me about last extraction and clean process?", state)
        modeling_decision_route = self.router.route("what u can toll me about lasts modeling process and decission takes for the orchestator?", state)
        meaning_route = self.router.route("why the number and what mean each hold long short ?", state)

        self.assertEqual(summary_route.intent, "show_latest_summary")
        self.assertEqual(legacy_route.intent, "show_legacy_status")
        self.assertEqual(help_route.intent, "help")
        self.assertEqual(ask_route.intent, "help")
        self.assertEqual(help_me_route.intent, "help")
        self.assertEqual(switch_es_route.intent, "set_language")
        self.assertEqual(switch_es_route.language, "es")
        self.assertEqual(switch_en_route.intent, "set_language")
        self.assertEqual(switch_en_route.language, "en")
        self.assertEqual(spanish_route.intent, "show_prediction")
        self.assertEqual(spanish_route.language, "es")
        self.assertEqual(sticky_spanish_route.intent, "show_asset_used")
        self.assertEqual(sticky_spanish_route.language, "es")
        self.assertEqual(extract_help_route.intent, "help")
        self.assertEqual(search_route.intent, "help")
        self.assertEqual(symbols_route.intent, "show_symbol_guide")
        self.assertEqual(spanish_symbols_route.intent, "show_symbol_guide")
        self.assertEqual(asset_used_route.intent, "show_asset_used")
        self.assertEqual(asset_used_es_route.intent, "show_asset_used")
        self.assertEqual(clean_data_route.intent, "show_clean_data")
        self.assertEqual(clean_data_hub_route.intent, "show_clean_data")
        self.assertEqual(clean_data_hub_es_route.intent, "show_clean_data")
        self.assertEqual(clean_symbols_route.intent, "show_clean_data")
        self.assertEqual(clean_metrics_route.intent, "show_clean_data")
        self.assertEqual(clean_metrics_es_route.intent, "show_clean_data")
        self.assertEqual(clean_schema_route.intent, "show_clean_data")
        self.assertEqual(clean_row_bare_route.intent, "show_clean_data")
        self.assertEqual(clean_row_row_route.intent, "show_clean_data")
        self.assertEqual(clean_row_natural_route.intent, "show_clean_data")
        self.assertEqual(clean_row_analysis_keyword_route.intent, "show_clean_data")
        self.assertEqual(clean_row_route.intent, "show_clean_data")
        self.assertEqual(clean_row_analysis_route.intent, "show_clean_data")
        self.assertEqual(clean_row_analysis_es_route.intent, "show_clean_data")
        self.assertEqual(extraction_report_route.intent, "show_extraction")
        self.assertEqual(extraction_report_en_route.intent, "show_extraction")
        self.assertEqual(market_metrics_route.intent, "show_market_metrics")
        self.assertEqual(market_metrics_es_route.intent, "show_market_metrics")
        self.assertEqual(market_metrics_fx_route.intent, "show_market_metrics")
        self.assertEqual(market_metrics_ambiguous_route.intent, "show_market_metrics")
        self.assertEqual(forex_extract_route.intent, "run_pipeline")
        self.assertEqual(forex_extract_route.tickers, ["EURUSD=X"])
        self.assertEqual(decision_route.intent, "show_decision_explanation")
        self.assertEqual(decision_route_es.intent, "show_decision_explanation")
        self.assertEqual(last_run_route.intent, "show_latest_summary")
        self.assertEqual(motor_route.intent, "show_stage_brief")
        self.assertEqual(motor_route.stage, "motor")
        self.assertEqual(groq_status_route.intent, "show_groq_status")
        self.assertEqual(session_status_route.intent, "show_session_status")
        self.assertEqual(session_status_full_route.intent, "show_session_status_full")
        self.assertEqual(session_status_full_route.stage, "session_status_full")
        self.assertEqual(session_status_full_es_route.intent, "show_session_status_full")
        self.assertEqual(session_status_full_es_route.stage, "session_status_full")
        self.assertEqual(mode_status_route.intent, "show_session_status")
        self.assertEqual(brain_status_route.intent, "show_session_status")
        self.assertEqual(mode_guide_route.intent, "show_mode_guide")
        self.assertEqual(mode_guide_route.stage, "local_only")
        self.assertEqual(groq_brain_mode_route.intent, "show_mode_guide")
        self.assertEqual(groq_brain_mode_route.stage, "groq_brain")
        self.assertEqual(mode_help_route.intent, "show_mode_guide")
        self.assertEqual(bare_mode_help_route.intent, "show_mode_guide")
        self.assertEqual(agents_route.intent, "show_agent_guide")
        self.assertEqual(bare_agents_route.intent, "show_agent_guide")
        self.assertEqual(shortcut_agents_route.intent, "show_agent_guide")
        self.assertEqual(shortcut_extraction_route.intent, "show_agent_card")
        self.assertEqual(shortcut_extraction_route.stage, "extraction")
        self.assertEqual(shortcut_cleaning_route.intent, "show_agent_card")
        self.assertEqual(shortcut_cleaning_route.stage, "cleaning")
        self.assertEqual(shortcut_modeling_route.intent, "show_agent_card")
        self.assertEqual(shortcut_modeling_route.stage, "modeling")
        self.assertEqual(shortcut_orchestrator_route.intent, "show_stage_brief")
        self.assertEqual(shortcut_orchestrator_route.stage, "orchestrator")
        self.assertEqual(shortcut_status_route.intent, "show_session_status")
        self.assertEqual(shortcut_full_status_route.intent, "show_session_status_full")
        self.assertEqual(shortcut_clean_data_route.intent, "show_clean_data")
        self.assertEqual(shortcut_modes_route.intent, "show_mode_guide")
        self.assertEqual(shortcut_help_route.intent, "help")
        self.assertEqual(shortcut_spanish_route.intent, "set_language")
        self.assertEqual(shortcut_spanish_route.language, "es")
        self.assertEqual(shortcut_english_route.intent, "set_language")
        self.assertEqual(shortcut_english_route.language, "en")
        self.assertEqual(bare_extraction_route.intent, "show_agent_card")
        self.assertEqual(bare_extraction_route.stage, "extraction")
        self.assertEqual(bare_cleaning_route.intent, "show_agent_card")
        self.assertEqual(bare_cleaning_route.stage, "cleaning")
        self.assertEqual(bare_modeling_route.intent, "show_agent_card")
        self.assertEqual(bare_modeling_route.stage, "modeling")
        self.assertEqual(bare_orchestrator_route.intent, "show_stage_brief")
        self.assertEqual(bare_orchestrator_route.stage, "orchestrator")
        self.assertEqual(bare_symbol_guide_route.intent, "show_symbol_guide")
        self.assertEqual(bare_mode_label_route.intent, "show_mode_guide")
        self.assertEqual(bare_mode_label_route.stage, "compare_binance")
        self.assertEqual(bare_ticker_route.intent, "run_pipeline")
        self.assertEqual(bare_ticker_route.tickers, ["AAPL"])
        self.assertIsNotNone(bare_ticker_route.start)
        self.assertIsNotNone(bare_ticker_route.end)
        self.assertEqual(run_lookup_route.intent, "show_asset_used")
        self.assertEqual(run_lookup_route.run_id, "run_0007")
        self.assertEqual(bare_run_lookup_route.intent, "show_session_status")
        self.assertEqual(bare_run_lookup_route.run_id, "run_0007")
        self.assertEqual(run_cleaning_route.intent, "show_cleaning")
        self.assertEqual(run_cleaning_route.run_id, "run_0007")
        self.assertEqual(run_cleaning_question_route.intent, "show_cleaning")
        self.assertEqual(run_cleaning_question_route.run_id, "run_0007")
        self.assertEqual(run_modeling_route.intent, "show_prediction")
        self.assertEqual(run_modeling_route.stage, "modeling")
        self.assertEqual(run_modeling_route.run_id, "run_0007")
        self.assertEqual(run_model_variables_route.intent, "show_model_variables")
        self.assertEqual(run_model_variables_route.stage, "model_variables")
        self.assertEqual(run_model_variables_route.run_id, "run_0007")
        self.assertEqual(run_model_variables_mid_sentence_route.intent, "show_model_variables")
        self.assertEqual(run_model_variables_mid_sentence_route.run_id, "run_0007")
        self.assertEqual(natural_model_variables_route.intent, "show_model_variables")
        self.assertEqual(natural_model_variables_route.stage, "model_variables")
        self.assertEqual(ask_extraction_card_route.intent, "show_agent_card")
        self.assertEqual(ask_extraction_card_route.stage, "extraction")
        self.assertEqual(ask_cleaning_card_route.intent, "show_agent_card")
        self.assertEqual(ask_cleaning_card_route.stage, "cleaning")
        self.assertEqual(ask_modeling_card_route.intent, "show_agent_card")
        self.assertEqual(ask_modeling_card_route.stage, "modeling")
        self.assertEqual(groq_brain_route.intent, "run_pipeline")
        self.assertTrue(groq_brain_route.experimental_groq_brain)
        self.assertEqual(groq_brain_route.tickers, ["AAPL"])
        self.assertEqual(groq_extract_route.intent, "show_stage_brief")
        self.assertEqual(groq_extract_route.stage, "extraction")
        self.assertEqual(use_extraction_route.intent, "show_agent_card")
        self.assertEqual(use_extraction_route.stage, "extraction")
        self.assertEqual(groq_clean_route.intent, "show_stage_brief")
        self.assertEqual(groq_clean_route.stage, "cleaning")
        self.assertEqual(groq_model_route.intent, "show_stage_brief")
        self.assertEqual(groq_model_route.stage, "modeling")
        self.assertEqual(groq_orch_route.intent, "show_stage_brief")
        self.assertEqual(groq_orch_route.stage, "orchestrator")
        self.assertEqual(orchestrator_route.intent, "show_stage_brief")
        self.assertEqual(orchestrator_route.stage, "orchestrator")
        self.assertEqual(ask_extraction_route.intent, "show_stage_brief")
        self.assertEqual(ask_extraction_route.stage, "extraction")
        self.assertEqual(ask_cleaning_route.intent, "show_stage_brief")
        self.assertEqual(ask_cleaning_route.stage, "cleaning")
        self.assertEqual(ask_modeling_route.intent, "show_stage_brief")
        self.assertEqual(ask_modeling_route.stage, "modeling")
        self.assertEqual(ask_orchestrator_route.intent, "show_stage_brief")
        self.assertEqual(ask_orchestrator_route.stage, "orchestrator")
        self.assertEqual(groq_here_route.intent, "show_stage_brief")
        self.assertEqual(groq_here_route.stage, "orchestrator")
        self.assertEqual(what_happened_route.intent, "show_stage_brief")
        self.assertEqual(what_happened_route.stage, "orchestrator")
        self.assertEqual(why_hold_route.intent, "show_stage_brief")
        self.assertEqual(why_hold_route.stage, "orchestrator")
        self.assertEqual(last_clean_route.intent, "show_cleaning")
        self.assertEqual(last_extraction_route.intent, "show_extraction")
        self.assertEqual(last_model_route.intent, "show_prediction")
        self.assertEqual(share_extraction_route.intent, "show_extraction")
        self.assertEqual(share_combined_route.intent, "show_stage_brief")
        self.assertEqual(share_combined_route.stage, "orchestrator")
        self.assertEqual(extraction_clean_route.intent, "show_stage_brief")
        self.assertEqual(extraction_clean_route.stage, "orchestrator")
        self.assertEqual(modeling_decision_route.intent, "show_stage_brief")
        self.assertEqual(modeling_decision_route.stage, "orchestrator")
        self.assertEqual(meaning_route.intent, "show_decision_explanation")

    def test_exact_shortcuts_bypass_groq_rerouting(self) -> None:
        class FakeGroqRouter:
            def __init__(self) -> None:
                self.enabled = True
                self.route_called = False

            def route(self, message, state, fallback):  # type: ignore[no-untyped-def]
                self.route_called = True
                return AssistantRoute(intent="show_cleaning", stage="cleaning")

            def synthesize(self, question, context, fallback_text):  # type: ignore[no-untyped-def]
                return fallback_text

        fake_groq = FakeGroqRouter()
        router = AssistantRouter(groq_router=fake_groq)
        state = AssistantState(session_id="test")

        route = router.route("4", state)

        self.assertFalse(fake_groq.route_called)
        self.assertEqual(route.intent, "show_agent_card")
        self.assertEqual(route.stage, "modeling")

    def test_search_yfinance_routes_to_run_pipeline(self) -> None:
        state = AssistantState(session_id="test")
        route = self.router.route("search yfinance for BTC", state)

        self.assertEqual(route.intent, "run_pipeline")
        self.assertIn("BTC-USD", route.tickers)

    def test_compare_binance_inferrs_asset_and_symbol(self) -> None:
        state = AssistantState(session_id="test")
        route = self.router.route(
            "compare yfinance with Binance for ETH-USD",
            state,
        )

        self.assertEqual(route.intent, "compare_sources")
        self.assertTrue(route.compare_binance)
        self.assertEqual(route.comparison_asset, "ETH")
        self.assertEqual(route.comparison_binance_symbol, "ETHUSDT")

    def test_pending_follow_up_keeps_run_intent_and_normalizes_crypto_ticker(self) -> None:
        state = AssistantState(
            session_id="test",
            pending_route={
                "intent": "run_pipeline",
                "tickers": ["BTC-USD"],
                "needs_follow_up": True,
                "follow_up_question": "Give me ticker(s) and date range.",
            },
        )

        route = self.router.route("BTC-USDT 2024-01-01 2025-01-01", state)

        self.assertEqual(route.intent, "run_pipeline")
        self.assertEqual(route.tickers, ["BTC-USD"])
        self.assertIsNotNone(route.start)
        self.assertIsNotNone(route.end)


class AssistantStatePersistenceTest(unittest.TestCase):
    def test_save_and_load_state_round_trips(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            state = AssistantState(
                session_id="session-1",
                last_run_id="run_0001",
                pending_task="extract",
                preferred_language="es",
            )
            save_state(str(root), state)

            loaded = load_state(str(root), "session-1")

            self.assertEqual(loaded.session_id, "session-1")
            self.assertEqual(loaded.last_run_id, "run_0001")
            self.assertEqual(loaded.pending_task, "extract")
            self.assertEqual(loaded.preferred_language, "es")


if __name__ == "__main__":
    unittest.main()
