from __future__ import annotations

from typing import Any, Dict, List

from assistant.contracts import AssistantRoute
from schemas.planner import PlannerStep


def _route_scope(route: AssistantRoute) -> Dict[str, str]:
    scope: Dict[str, str] = {}
    if route.run_id:
        scope["run_id"] = route.run_id
    if route.secondary_run_id:
        scope["secondary_run_id"] = route.secondary_run_id
    if route.stage:
        scope["stage"] = route.stage
    if route.tickers:
        scope["ticker"] = route.tickers[0]
    return scope


class AssistantToolLayer:
    """Maps routed intents to an internal tool sequence.

    The runtime still executes handlers directly, but the planner now exposes
    the execution shape explicitly so the assistant can evolve into a real
    planner/executor loop without inventing a second contract later.
    """

    def build_steps(self, route: AssistantRoute, context_snapshot: Dict[str, Any] | None = None) -> List[PlannerStep]:
        scope = _route_scope(route)
        if context_snapshot:
            if context_snapshot.get("run_id") and "run_id" not in scope:
                scope["run_id"] = str(context_snapshot["run_id"])
            if context_snapshot.get("stage") and "stage" not in scope:
                scope["stage"] = str(context_snapshot["stage"])
            for key in ("answer_mode", "certainty", "question_focus"):
                value = context_snapshot.get(key)
                if value:
                    scope[key] = str(value)
            source_mode = context_snapshot.get("source_mode")
            if source_mode:
                scope["source_mode"] = str(source_mode)
        context_tool = PlannerStep(
            tool="load_context_bundle",
            purpose="Load a compact session/run context snapshot before final response synthesis.",
            arguments={key: value for key, value in scope.items() if isinstance(value, str)},
        )
        render_tool = PlannerStep(tool="render_response", purpose="Compose the final grounded reply.", arguments=scope)
        bundle_tool = PlannerStep(tool="load_run_bundle", purpose="Load manifest/result/summary/error for the target run.", arguments=scope)
        comparison_bundle_tool = PlannerStep(
            tool="load_run_comparison_bundle",
            purpose="Load manifest/result/summary/error for two target runs.",
            arguments=scope,
        )
        web_tool = PlannerStep(
            tool="retrieve_web_facts",
            purpose="Retrieve external facts when local artifacts do not fully answer the question.",
            arguments=scope,
        )
        grounding_tool = PlannerStep(
            tool="merge_grounding_facts",
            purpose="Merge local artifact facts with optional external facts before responding.",
            arguments=scope,
        )

        if route.intent in {"run_pipeline", "compare_sources"}:
            return [
                PlannerStep(
                    tool="build_pipeline_request",
                    purpose="Normalize the conversational route into an executable pipeline request.",
                    arguments=scope,
                ),
                PlannerStep(
                    tool="execute_pipeline",
                    purpose="Run extraction, cleaning, modeling, and orchestration for the requested inputs.",
                    arguments=scope,
                ),
                PlannerStep(
                    tool="load_run_bundle",
                    purpose="Reload artifacts generated by the pipeline run.",
                    arguments=scope,
                ),
                render_tool,
            ]

        if route.intent in {
            "show_semantic_lookup",
            "show_latest_summary",
            "show_extraction",
            "show_cleaning",
            "show_prediction",
            "show_model_variables",
            "show_legacy_status",
            "show_asset_used",
            "show_market_type",
            "show_clean_data",
            "show_market_metrics",
            "show_decision_explanation",
            "show_stage_brief",
            "show_session_status",
            "show_session_status_full",
            "show_turn_trace",
            "continue_task",
            "help",
        }:
            if route.source_mode in {"web", "mixed"}:
                return [context_tool, bundle_tool, web_tool, grounding_tool, render_tool]
            return [context_tool, bundle_tool, render_tool]

        if route.intent in {
            "show_mode_guide",
            "show_agent_guide",
            "show_agent_card",
            "show_symbol_guide",
            "show_groq_status",
            "show_web_status",
            "show_assistant_scorecard",
            "show_turn_trace",
            "show_source_scope",
            "show_time_status",
            "set_language",
            "greet",
        }:
            return [context_tool, render_tool]

        if route.intent == "show_run_comparison":
            return [context_tool, comparison_bundle_tool, render_tool]

        return [
            context_tool,
            PlannerStep(
                tool="fallback_router_resolution",
                purpose="Use the deterministic fallback route when the request is still ambiguous.",
                arguments=scope,
            ),
            render_tool,
        ]
